# Generated by Django 4.2.6 on 2023-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(blank=True, null=True)),
                ('Author', models.TextField(blank=True, null=True)),
                ('Link', models.TextField(blank=True, null=True)),
                ('Bookshelf', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
