# Generated by Django 4.2.5 on 2023-10-26 18:25

from django.core.management import call_command
from django.db import migrations


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata","books.json")


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_remove_book_author_remove_book_link_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data)
    ]
