# Generated by Django 4.2.6 on 2023-10-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_rename_link_book_link_remove_book_author_and_more'),
        ('appmain', '0006_favorite'),
    ]

    operations = [
    ]
