# Generated by Django 4.2.6 on 2023-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0008_auto_20231030_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='link',
            new_name='Link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
