# Generated by Django 4.2.4 on 2023-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('book_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
