# Generated by Django 4.2.6 on 2023-10-28 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('issue_type', models.CharField(choices=[('DM', 'Damaged'), ('MI', 'Missing Information'), ('OT', 'Others')], max_length=2)),
                ('other_issue', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Under Review', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
