# Generated by Django 4.2.6 on 2023-10-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0002_report_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='other_issue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
