# Generated by Django 4.2.6 on 2023-10-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0003_alter_report_other_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('Buku Rusak', 'Damaged'), ('Informasi Hilang', 'Missing Information'), ('Masalah Lainnya', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='Under Review', max_length=200),
        ),
    ]
