# Generated by Django 4.2.6 on 2023-10-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0004_alter_report_issue_type_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
