# Generated by Django 4.2.6 on 2023-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0005_alter_report_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
