# Generated by Django 4.2.6 on 2023-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0006_alter_report_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
