# Generated by Django 5.0 on 2023-12-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0009_remove_report_attachment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(default='No Name', max_length=200),
        ),
    ]
