# Generated by Django 5.0 on 2023-12-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0010_report_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
