# Generated by Django 5.0 on 2023-12-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulreport', '0012_report_admin_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='admin_response',
            field=models.TextField(default='', null=True),
        ),
    ]
